version: 2
updates:
  - package-ecosystem: "dart" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Rome"
