name: Continous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  dependabot:
    name: 'Dependabot'
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ (github.actor == 'dependabot[bot]' && github.event_name == 'pull_request') || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter clean && flutter pub get && flutter pub upgrade --major-versions

      - name: Auto-merge PRs
        uses: "pascalgn/automerge-action@v0.15.3"
        if: ${{ success() }}
        with:
          merge_method: "squash"
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Close PR if tests fail
        uses: peter-evans/close-pull@v3.0.0
        if: ${{ failure() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment: "Tests failed, closing this PR. Please fix the tests and open a new PR."
